# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true
platform :ios, 13.0

target 'ChatSDKIntegrationTesting' do
  # Comment the next line if you don't want to use dynamic frameworks


  pod "ChatSDK"
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/Upload"
  pod "ChatSDKFirebase/Push"

  pod 'SDWebImage', '~> 5.0'
#  pod "MessageModules/StickerMessage", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/MessageModules.podspec"
#  
#  pod "MessageModules/VideoMessage", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/MessageModules.podspec"
#  pod "MessageModules/AudioMessage", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/MessageModules.podspec"
#  pod "MessageModules/KeyboardOverlayOptions", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/MessageModules.podspec"
#  pod "MessageModules/FileMessage", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/MessageModules.podspec"
#  pod "MessageModules/GiphyMessage", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/MessageModules.podspec"
#  
#  pod "FirebaseModules/FirebaseBlocking", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/FirebaseModules.podspec"
#  pod "FirebaseModules/FirebaseLastOnline", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/FirebaseModules.podspec"
#  pod "FirebaseModules/FirebaseTypingIndicator", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/FirebaseModules.podspec"
#  pod "FirebaseModules/FirebaseReadReceipts", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/FirebaseModules.podspec"
#  
#  pod "ContactBook/ContactBook", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/ContactBook.podspec"
#
#  pod "Encryption/Encryption", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/Encryption.podspec"
#  
#  pod "Licensing", :path => "/Users/mapple.pk/Desktop/WorkSpace/ChatSDKIntegrationTesting/Licensing.podspec"

  target 'ChatSDKIntegrationTestingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatSDKIntegrationTestingUITests' do
    # Pods for testing
  end

end


post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #config.build_settings['OTHER_LDFLAGS'] = '$(inherited)'
            #config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            #config.build_settings['ENABLE_BITCODE'] = "YES"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
