# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebas-Handling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebas-Handling

 pod 'Firebase'
  pod 'FirebaseCoreInternal'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'

end
